services:
    tas2580.seourls.listener:
        class: tas2580\seourls\event\listener
        arguments:
            - @config
            - @template
            - @request
            - @user
        tags:
            - { name: event.listener }
